DROP SEQUENCE IF EXISTS aingredients;
DROP SEQUENCE IF EXISTS arecipes;
DROP SEQUENCE IF EXISTS ausers;

CREATE SEQUENCE aingredients START 1 INCREMENT 1;
CREATE SEQUENCE arecipes START 1 INCREMENT 1;
CREATE SEQUENCE ausers START 1 INCREMENT 1;